config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'logout', to: 'devise/sessions#destroy'
  end

  devise_for :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :recipes do
    resources :comments, only: [:index, :new, :create]
  end

  # resource :session, only: [:show, :new, :create, :destroy]

  root to: 'recipes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    belongs_to :user, optional: true
    has_many :recipes
    has_many :comments
    has_many :commented_recipes, 
        through: :comments, 
        source: :commentable, 
        source_type: 'Recipe',
        foreign_key: :commentable_type, 
        class_name: 'Recipe'
    has_many :logs, as: :loggable
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :comments, as: :commentable
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :author
    belongs_to :commentable, polymorphic: true
    has_many :logs, as: :loggable
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :recipe_ingredients
    has_many :recipes, through: :recipe_ingredients
    has_many :comments, as: :commentable
    has_many :logs, as: :loggable
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :loggable, polymorphic: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :author
    has_many :recipe_ingredients
    has_many :ingredients, through: :recipe_ingredients
    has_many :comments, as: :commentable
    has_one_attached :image
    has_many :transactions
    has_many :logs, as: :loggable

    validates :name, presence: true
    validates :name, uniqueness: true
    validates :difficulty, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }

    accepts_nested_attributes_for :comments

    scope :very_difficult, -> { where(difficulty: 5) }
    scope :sold, -> { joins(:transactions) }

    after_create :log_create
    after_update :log_update

    def to_s
        "Recipe #{id}; #{name}, #{difficulty}"
    end

    def log_create
        logs.create! body: 'Created!'
    end

    def log_update
        logs.create! body: 'Updated!'
    end
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
    belongs_to :recipe
    belongs_to :ingredient
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :seller, class_name: 'User'
  belongs_to :buyer, class_name: 'User'
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  has_one :author
  accepts_nested_attributes_for :author

  has_many :purchases, class_name: 'Transaction', foreign_key: 'buyer_id'
  has_many :sales, class_name: 'Transaction', foreign_key: 'seller_id'

  has_many :purchased_recipes, through: :purchases, source: :recipe
  has_many :sold_recipes, through: :sales, source: :recipe

  has_many :logs, as: :loggable

  scope :sellers, -> { distinct.joins(:sales) }
  scope :buyers, -> { distinct.joins(:purchases) }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise \
    :database_authenticatable,
    :registerable,
    :recoverable,
    :rememberable,
    :validatable,
    :trackable,
    :timeoutable, timeout_in: 30.minutes

  def admin?; false; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit

    # skip_before_action :verify_authenticity_token
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [
        author_attributes: [ :name, :editor ]
      ])
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    include Unauthorized
    before_action :authenticate_user!
    rescue_from Pundit::NotAuthorizedError, with: :unauthorised

    def index
        @recipes = Recipe.all
    end

    def show
        @recipe = Recipe.find params[:id]

        respond_to do |format|
            format.html
            format.text { render plain: @recipe }
            format.json { render json: @recipe }
        end
    end

    def new
        @recipe = Recipe.new
    end

    def create
        # author = Author.find params[:recipe][:author_id]
        # @recipe = author.recipes.build permitted_params
        # Or permit author_id in the mass assignment for the receipe.
        @recipe = Recipe.new permitted_params

        respond_to do |format|
            if @recipe.save
                format.html { redirect_to @recipe }
            else
                format.html { render :new }
            end
        end
    end

    def edit
        @recipe = Recipe.find(params[:id])
        authorize @recipe
    end

    def update
        @recipe = Recipe.find(params[:id])
        authorize @recipe

        respond_to do |format|
            if @recipe.update(permitted_params)
                format.html { redirect_to @recipe }
            else
                format.html { render :edit }
            end
        end
    end

    def permitted_params
        params.required(:recipe).permit(
            :name, :difficulty, :image, :author_id, ingredient_ids: [], comments_attributes: [ :author_id, :text ]
        ) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <p class="notice"><%= flash[:notice] %></p>
    <p class="alert"><%= flash[:alert] %></p>
    <header>
      <p>Hello, <%= current_user&.email || 'Anonymous' %>!</p>
    </header>
    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with model: recipe, class: 'recipe' do |form| %>
    <% if recipe.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>
            <ul>
                <% recipe.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name %>
    </div>

    <div class="field">
        <%= form.label :difficulty %>
        <%= form.range_field :difficulty, in: 1..5 %>
    </div>

    <div class="field">
        <%= form.label :image %>
        <%= form.file_field :image %>
    </div>

    <div class="field">
        <%= form.label :author_id %>
        <%= form.collection_select :author_id, Author.all, :id, :name %>
    </div>

    <div class="field ingredients">
        <%= form.label :ingredients %>
        <%= form.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name %>
    </div>

    <div class="field">
        <%= form.label :comment %>
        <%= form.fields_for :comments, recipe.comments.build(author_id: current_user.author.id) do |comment_form| %>
            <%= comment_form.hidden_field :author_id %>
            <%= comment_form.text_area :text %>
        <% end %>
    </div>

    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

app/views/recipes/_message.html.erb
<li><%= message %></li>

app/views/recipes/edit.html.erb
<h1>Edit Redcipe</h1>

<%= render 'form', recipe: @recipe %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Difficulty</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.name %></td>
        <td><%= recipe.difficulty %></td>
        <td><%= recipe.author.name %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td>
          <% if policy(recipe).edit? %>
            <%= link_to 'Edit', edit_recipe_path(recipe) %>
          <% else %>
            &nbsp;
          <% end %>
        </td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= form_with model: @recipe do |form| %>
    <% if @recipe.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>
            <ul>
                <% @recipe.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name %>
        <% if @recipe.errors.full_messages_for(:name) %>
            <%= @recipe.errors.full_messages_for(:name) %>
        <% end %>
    </div>

    <div class="field">
        <%= form.label :difficulty %>
        <%= form.range_field :difficulty, in: 1..10 %>
    </div>

    <div class="field">
        <%= form.label :author_id %>
        <%= form.collection_select :author_id, Author.all, :id, :name %>
    </div>

    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

app/views/recipes/show.html.erb
<div class="recipe show">
    <h1>Recipe</h1>

    <div>
        <strong>Name</strong>
        <%= @recipe.name %>
    </div>

    <div>
        <strong>Difficulty</strong>
        <%= @recipe.difficulty %>
    </div>

    <div>
        <strong>Author</strong>
        <%= @recipe.author.name %>
    </div>

    <% if @recipe.image.attached? %>
        <div>
            <%= image_tag url_for(@recipe.image), width: '250px' %>
        </div>
    <% end %>

    <div class='ingredients'>
        <strong>Ingredients</strong>
        <ul>
            <% @recipe.ingredients.each do |ingredient| %>
                <li class='ingredient'><%= ingredient.name %></li>
            <% end %>
        </ul>
    </div>

    <div class='comments'>
        <strong>Comments</strong>
        <ul class='comment'>
            <% @recipe.comments.each do |comment| %>
                <li>
                    <div>
                        <span>
                            By <%= comment.author.name %>
                        </span>
                        <span>
                            <%= distance_of_time_in_words_to_now comment.created_at %>

                        </span>
                    </div>
                    <div><%= comment.text %></div>
                </li>
            <% end %>
        </ul>
</div>

app/views/shared/_heading.html.erb
<h1>Messages</h1>